// States and Union Territories
import { v4 as uuidv4 } from 'uuid';

export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar",
  "Chandigarh",
  "Daman, Diu, Dadra & Nagar Haveli",
  "Delhi NCR",
  "Jammu & Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

// Categories/Professions
export const categories = [
  "Medical",
  "Engineering", 
  "Police / Defense",
  "Banking",
  "Railway",
  "Nursing",
  "Pharmacy",
  "Post Office",
  "Teaching",
  "Law / Judiciary",
  "Agriculture",
  "Hotel Management",
  "Aviation",
  "Scientist",
  "PSU / Govt",
  "Sports Quota",
  "Apprentice",
  "Clerk / Assistant",
  "Forest / Environment"
];

// Qualifications
export const qualifications = [
  "10th Pass",
  "12th Pass",
  "Graduate",
  "Diploma",
  "B.Tech / B.E",
  "ITI",
  "Post Graduate",
  "MBBS / BDS",
  "Nursing (B.Sc / GNM / ANM)",
  "B.Ed / TET",
  "MBA / CA",
  "PhD / M.Phil",
  "B.Sc",
  "M.Sc",
  "B.Com",
  "M.Com",
  "LLB",
  "GATE",
  "NET",
  "DNB",
  "MD",
  "MS"
];

// Recruitment Boards
export const recruitmentBoards = [
  "UPSC", "SSC", "NTA", "GATE", "UGC NET", "IBPS", "SBI", "RBI", "LIC", 
  "PNB", "Bank of Baroda", "Canara Bank", "RRB (Railways)", "RRC (Group D)", 
  "Metro Rail", "Indian Army", "Indian Navy", "Indian Air Force", "BSF", 
  "CRPF", "CISF", "ITBP", "SSB", "State Police", "DRDO", "ISRO", "BARC", 
  "CSIR", "ICMR", "ICAR", "IIT", "NIT", "AIIMS", "ONGC", "IOCL", "NTPC", 
  "SAIL", "BHEL", "GAIL", "AAI", "FCI", "KVS", "NVS", "CTET", "UPPSC", 
  "UPSSSC", "BPSC", "BSSC", "RPSC", "RSMSSB", "MPSC", "MPPSC", "HSSC", 
  "JPSC", "JSSC", "WBPSC", "KPSC", "TNPSC", "TSPSC", "APPSC", "OPSC"
];

// Mock Job Data
export const mockJobs = [
  {
    id: 'sbi-po-2026',
    title: 'SBI PO Recruitment 2026',
    organization: 'State Bank of India',
    description: 'Apply Online for 1500 Probationary Officer Posts',
    qualification: ['Graduate'],
    lastDate: '2026-07-08',
    state: 'Across India',
    category: 'Banking',
    board: 'SBI',
    type: 'recruitment',
    status: 'active',
    isLive: true,
    salary: '₹41,960 - ₹58,920',
    posts: 1500,
    applyLink: 'https://sbi.co.in/careers',
    notificationPdf: '/pdfs/sbi-po-2026.pdf',
    createdAt: '2026-06-20',
    tags: ['Banking', 'PO', 'Graduate', 'Across India']
  },
  {
    id: 'rcfl-operator-2026',
    title: 'RCFL Operator Chemical Trainee',
    organization: 'Rashtriya Chemicals and Fertilizers Limited',
    description: 'Call Letter 2026 Download IBPS Link',
    qualification: ['B.Sc', 'Diploma'],
    lastDate: '2026-06-30',
    state: 'Maharashtra',
    category: 'PSU / Govt',
    board: 'IBPS',
    type: 'recruitment',
    status: 'active',
    isLive: true,
    salary: '₹25,000 - ₹40,000',
    posts: 50,
    applyLink: 'https://ibps.in',
    notificationPdf: '/pdfs/rcfl-operator-2026.pdf',
    createdAt: '2026-06-18',
    tags: ['PSU', 'Chemical', 'Trainee', 'Maharashtra']
  },
  {
    id: 'nilgiris-lab-tech-2026',
    title: 'Nilgiris Lab Technician Grade II',
    organization: 'Nilgiris District Health Society',
    description: 'Apply for 03 Posts',
    qualification: ['Diploma'],
    lastDate: '2026-06-29',
    state: 'Tamil Nadu',
    category: 'Medical',
    board: 'TNPSC',
    type: 'recruitment',
    status: 'active',
    isLive: false,
    salary: '₹19,500 - ₹62,000',
    posts: 3,
    applyLink: 'https://tnpsc.gov.in',
    notificationPdf: '/pdfs/nilgiris-lab-tech-2026.pdf',
    createdAt: '2026-06-15',
    tags: ['Medical', 'Lab Technician', 'Tamil Nadu']
  },
  {
    id: 'deoghar-recruitment-2026',
    title: 'Deoghar Recruitment Camp 2026',
    organization: 'Deoghar District Administration',
    description: 'for 290 Posts Walk-in on 20 June',
    qualification: ['10th Pass', '12th Pass', 'GDA'],
    lastDate: '2026-06-20',
    state: 'Jharkhand',
    category: 'Clerk / Assistant',
    board: 'JPSC',
    type: 'walkin',
    status: 'active',
    isLive: true,
    salary: '₹15,000 - ₹30,000',
    posts: 290,
    applyLink: 'https://jharkhand.gov.in',
    notificationPdf: '/pdfs/deoghar-recruitment-2026.pdf',
    createdAt: '2026-06-10',
    tags: ['Walk-in', 'Multiple Posts', 'Jharkhand']
  },
  {
    id: 'kulgam-mission-shakti-2026',
    title: 'Kulgam Mission Shakti Recruitment 2026',
    organization: 'Mission Shakti, Kulgam',
    description: 'for OSC and DHEW Posts',
    qualification: ['10th Pass', 'Graduate', 'LLB'],
    lastDate: '2026-07-03',
    state: 'Jammu & Kashmir',
    category: 'Social Work',
    board: 'JKSSB',
    type: 'recruitment',
    status: 'active',
    isLive: false,
    salary: '₹20,000 - ₹45,000',
    posts: 50,
    applyLink: 'https://jkssb.nic.in',
    notificationPdf: '/pdfs/kulgam-mission-shakti-2026.pdf',
    createdAt: '2026-06-05',
    tags: ['Mission Shakti', 'Women Empowerment', 'J&K']
  },
  {
    id: 'up-rojgaar-sports-coach-2026',
    title: 'UP Rojgaar Sangam Sports Coach',
    organization: 'UP Rojgaar Sangam',
    description: 'Salary ₹25000',
    qualification: ['12th Pass'],
    lastDate: '2026-06-24',
    state: 'Uttar Pradesh',
    category: 'Sports Quota',
    board: 'UPSSSC',
    type: 'recruitment',
    status: 'active',
    isLive: true,
    salary: '₹25,000',
    posts: 25,
    applyLink: 'https://uprojgaar.in',
    notificationPdf: '/pdfs/up-rojgaar-sports-coach-2026.pdf',
    createdAt: '2026-06-01',
    tags: ['Sports', 'Coach', 'Uttar Pradesh']
  },
  {
    id: 'up-rojgaar-conductor-2026',
    title: 'UP Rojgaar Sangam Conductor',
    organization: 'UP Rojgaar Sangam',
    description: 'Apply for 99 Posts',
    qualification: ['12th Pass', 'CCC'],
    lastDate: '2026-06-24',
    state: 'Uttar Pradesh',
    category: 'Transport',
    board: 'UPSSSC',
    type: 'recruitment',
    status: 'active',
    isLive: false,
    salary: '₹21,700 - ₹69,100',
    posts: 99,
    applyLink: 'https://uprojgaar.in',
    notificationPdf: '/pdfs/up-rojgaar-conductor-2026.pdf',
    createdAt: '2026-05-28',
    tags: ['Conductor', 'Transport', 'Uttar Pradesh']
  },
  {
    id: 'nhm-kalahandi-2026',
    title: 'NHM Kalahandi In-House Selection',
    organization: 'National Health Mission, Kalahandi',
    description: 'for 63 Posts Walk-in Dates',
    qualification: ['10th Pass', '12th Pass', 'ANM', 'B.Pharm', 'BHMS', 'Diploma', 'MBBS', 'Post Graduate'],
    lastDate: '2026-07-17',
    state: 'Odisha',
    category: 'Medical',
    board: 'OPSC',
    type: 'walkin',
    status: 'active',
    isLive: true,
    salary: '₹15,000 - ₹50,000',
    posts: 63,
    applyLink: 'https://nhm.gov.in',
    notificationPdf: '/pdfs/nhm-kalahandi-2026.pdf',
    createdAt: '2026-05-20',
    tags: ['Health', 'Walk-in', 'Multiple Qualifications', 'Odisha']
  },
  {
    id: 'mpsc-mizoram-jao-2026',
    title: 'MPSC Mizoram JAO Ex-Servicemen',
    organization: 'Mizoram Public Service Commission',
    description: 'Apply by 24 July',
    qualification: ['Graduate'],
    lastDate: '2026-07-24',
    state: 'Mizoram',
    category: 'Defense',
    board: 'MPSC',
    type: 'recruitment',
    status: 'upcoming',
    isLive: false,
    salary: '₹25,000 - ₹60,000',
    posts: 15,
    applyLink: 'https://mpsc.mizoram.gov.in',
    notificationPdf: '/pdfs/mpsc-mizoram-jao-2026.pdf',
    createdAt: '2026-05-15',
    tags: ['Ex-Servicemen', 'JAO', 'Mizoram']
  },
  {
    id: 'icmr-bmhrc-faculty-2026',
    title: 'ICMR BMHRC Faculty Medical',
    organization: 'ICMR - Regional Medical Research Centre',
    description: 'Apply for Professor and Assistant Professor Posts',
    qualification: ['DNB', 'MBBS', 'MD', 'MS', 'Post Graduate'],
    lastDate: '2026-07-14',
    state: 'Odisha',
    category: 'Medical',
    board: 'ICMR',
    type: 'recruitment',
    status: 'active',
    isLive: true,
    salary: '₹67,700 - ₹2,08,700',
    posts: 10,
    applyLink: 'https://icmr.nic.in',
    notificationPdf: '/pdfs/icmr-bmhrc-faculty-2026.pdf',
    createdAt: '2026-05-10',
    tags: ['Faculty', 'Medical', 'Professor', 'Odisha']
  },
  {
    id: 'maharashtra-stenographer-2026',
    title: 'Maharashtra Social Welfare Stenographer',
    organization: 'Social Welfare Department, Maharashtra',
    description: 'Date and Instructions',
    qualification: ['10th Pass', '12th Pass', 'Graduate'],
    lastDate: '2026-06-30',
    state: 'Maharashtra',
    category: 'Clerk / Assistant',
    board: 'MPSC',
    type: 'exam',
    status: 'active',
    isLive: false,
    salary: '₹25,500 - ₹81,100',
    posts: 50,
    applyLink: 'https://mahasocialwelfare.in',
    notificationPdf: '/pdfs/maharashtra-stenographer-2026.pdf',
    createdAt: '2026-04-25',
    tags: ['Stenographer', 'Social Welfare', 'Maharashtra']
  },
  {
    id: 'nsg-act-2025',
    title: 'NSG Act 2025 Second Set Provisions',
    organization: 'National Security Guard',
    description: 'Notification PDF Download',
    qualification: ['Graduate'],
    lastDate: '2026-07-01',
    state: 'Across India',
    category: 'Police / Defense',
    board: 'MHA',
    type: 'notification',
    status: 'active',
    isLive: true,
    salary: 'N/A',
    posts: 0,
    applyLink: 'https://nsg.gov.in',
    notificationPdf: '/pdfs/nsg-act-2025.pdf',
    createdAt: '2026-04-01',
    tags: ['NSG', 'Act', 'Notification']
  }
];

// Onboarding interests
export const onboardingInterests = [
  { id: 'banking', name: 'Banking Jobs', icon: 'bank' },
  { id: 'medical', name: 'Medical Jobs', icon: 'heart' },
  { id: 'engineering', name: 'Engineering Jobs', icon: 'settings' },
  { id: 'defense', name: 'Defense Jobs', icon: 'shield' },
  { id: 'railway', name: 'Railway Jobs', icon: 'train' },
  { id: 'teaching', name: 'Teaching Jobs', icon: 'book' },
  { id: 'psu', name: 'PSU Jobs', icon: 'building' },
  { id: 'state-govt', name: 'State Government', icon: 'map' },
  { id: 'central-govt', name: 'Central Government', icon: 'flag' },
];

// Featured jobs for homepage
export const featuredJobs = mockJobs.filter(job => job.isLive).slice(0, 6);

// Latest notifications
export const latestNotifications = [
  {
    id: 1,
    title: 'New SBI PO Recruitment Announced',
    message: '1500 Probationary Officer posts available. Apply before 8th July 2026.',
    time: '2 hours ago',
    read: false,
    jobId: 'sbi-po-2026'
  },
  {
    id: 2,
    title: 'RCFL Operator Call Letter Released',
    message: 'Download your call letter for Operator Chemical Trainee exam.',
    time: '5 hours ago',
    read: false,
    jobId: 'rcfl-operator-2026'
  },
  {
    id: 3,
    title: 'UP Rojgaar Sports Coach Walk-in',
    message: 'Walk-in interview for Sports Coach positions on 24th June.',
    time: '1 day ago',
    read: true,
    jobId: 'up-rojgaar-sports-coach-2026'
  }
];

// User profile mock data
export const userProfile = {
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  phone: '+91 98765 43210',
  state: 'Maharashtra',
  preferredCategories: ['Banking', 'Engineering'],
  preferredQualifications: ['Graduate', 'B.Tech'],
  notificationSettings: {
    email: true,
    push: true,
    sms: false,
  },
  createdAt: '2026-01-15',
  lastLogin: '2026-06-24T10:30:00',
};
